/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-1",
    "aws_appsync_graphqlEndpoint": "https://4lzmsis4wva53k3pwyvkxorcgy.appsync-api.us-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-74so3jigsngsxha3nvlz42xbdi",
    "aws_cognito_identity_pool_id": "us-west-1:57e88ade-eb08-451b-bca9-eb10a2392179",
    "aws_cognito_region": "us-west-1",
    "aws_user_pools_id": "us-west-1_MXVJWHwXS",
    "aws_user_pools_web_client_id": "2k8orsao3n7248hmvgmcd2fntn",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "pdf-storage171945-dev",
    "aws_user_files_s3_bucket_region": "us-west-1"
};


export default awsmobile;
